name = "lean-antithesis"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanAntithesis"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false # no copyright/license headers
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0-rc2"

[[lean_lib]]
name = "LeanAntithesis"
